baseURL: https://conformance.ipfs.tech/
languageCode: en-us
title: Gateway Conformance Dashboard

theme:
  - conformance

markup:
  goldmark:
    renderer:
      unsafe: true
blackfriday:
  extensions: hardLineBreak

# menu:
#   main:

taxonomies:
  ipip: ipips
  test: tests
  result: results
