name: Release Fixtures
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Release]
    types:
      - completed
    

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: gateway-conformance
      - name: Generate Fixtures
        env:
          W3STORAGE_TOKEN: ${{ secrets.W3STORAGE_TOKEN }}
        run: |
          make fixtures.car
        working-directory: gateway-conformance
      - name: Upload fixtures
        uses: web3-storage/add-to-web3@v2
        with:
          web3_token: ${{ secrets.W3STORAGE_TOKEN }}
          path_to_add: 'gateway-conformance/fixtures.car'
