name: Test Tooling

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4
      - uses: actions/checkout@v3
        with:
          path: 'gateway-conformance'
      - uses: protocol/cache-go-action@v1
      - name: Run the tests
        shell: bash
        working-directory: ./gateway-conformance
        run: |
          go test ./tooling/...